networks:
  main: null

version: '2'

services:

  dev_db:
    container_name: dev_db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    image: postgres:12
    networks:
      main:
        aliases:
          - dev_db
    ports:
      - 6000:5432
    volumes:
      - $HOME/data:/var/lib/postgresql/data

  jsp-redis:
    container_name: jsp-redis
    image: redis
    networks:
      main:
        aliases:
          - jsp-redis

  jsp-web:
    build: 
      context: .
      args:
        DOCKER_BUILD_ENV: development
    image: jsp
    working_dir: /rails
    container_name: jsp-web
    env_file:
      - .env.development
    depends_on:
      - dev_db
      - jsp-redis
    networks:
      main:
        aliases:
          - jsp
    ports:
      - 3012:3012
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - .:/rails
